version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "carbon-credit-inventory-management"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-himqt8mrtbdf"
s3_prefix = "carbon-credit-inventory-management"
region = "ap-south-1"
profile = "eagle-brand-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
