AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 128
    Timeout: 15

Resources:

  # S3 Bucket
  carbonRiskTemplateBucket:
    Type: AWS::S3::Bucket

  # Functions
  S3TriggeredLambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: csv-upload
      Handler: csv-upload
      Description: Function that is called when a file is stored in S3.
      Runtime: go1.x
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        carbonRiskTemplateBucket:
          Type: S3
          Properties:
            Bucket: !Ref carbonRiskTemplateBucket
            Events: 's3:ObjectCreated:*'

  # Permissions
  AllowS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref S3TriggeredLambdaHandler
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt carbonRiskTemplateBucket.Arn